server:
  port: 8083

spring:
  application:
    name: enrollment-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://cloudblitz:redhat123@cloudblitz-cluster.0xef32k.mongodb.net/cb_auth?retryWrites=true&w=majority&appName=cdec-dev}

jwt:
  secret: ${JWT_SECRET:CloudBlitzJWTSecretKeyForSecureAuthentication2024!@#}

course:
  service:
    url: ${COURSE_SERVICE_URL:http://localhost:8082/api/courses}

logging:
  level:
    in.cloudblitz.enrollment: DEBUG
