server:
  port: 8083

spring:
  application:
    name: enrollment-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://atulyw:R8RfzxlNDb6Z68pe@cdec-dev.et2yiaw.mongodb.net/cb_enrollments?retryWrites=true&w=majority&appName=cdec-dev}

jwt:
  secret: ${JWT_SECRET:CloudBlitzJWTSecretKeyForSecureAuthentication2024!@#}

logging:
  level:
    in.cloudblitz.enrollment: DEBUG
