server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://atulyw:R8RfzxlNDb6Z68pe@cdec-dev.et2yiaw.mongodb.net/cb_courses?retryWrites=true&w=majority&appName=cdec-dev}

logging:
  level:
    in.cloudblitz.course: DEBUG
