apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: cloudblitz
  labels:
    app: enrollment-service
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: enrollment-service

