apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: cloudblitz
  labels:
    app: course-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: course-service

